# Generated by Django 4.0 on 2021-12-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='docs/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
