# Generated by Django 4.0 on 2022-01-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_folder_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='folder_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.folder'),
        ),
        migrations.AddField(
            model_name='document',
            name='topic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.topic'),
        ),
    ]
