# Generated by Django 4.0 on 2022-01-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_folder_id_document_topic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='folder_id',
            new_name='folder',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
